### PR TITLE
local image hosting, new action stuff

### PR DESCRIPTION
**Pull request by ljang0**
added upload to the action space, a page focus safeguard, local hosting of images to combat broken url bugs/longetivity of the benchmark, and new config files to adjust for this

### CODE REVIEW

**Comment by Ilya-Krylov** [comment]
\_\_HOMEPAGE__/static/input_images/classifieds/53/input_0.png
\_\_HOMEPAGE__/static/input_images/classifieds/54/input_0.png
\_\_HOMEPAGE__/static/input_images/classifieds/55/input_0.png

\_\_HOMEPAGE__/static/input_images/reddit/155/input_0.png
\_\_HOMEPAGE__/static/input_images/reddit/157/input_0.png
\_\_HOMEPAGE__/static/input_images/reddit/165/input_0.png
\_\_HOMEPAGE__/static/input_images/reddit/176/input_0.png
\_\_HOMEPAGE__/static/input_images/reddit/177/input_0.png
\_\_HOMEPAGE__/static/input_images/reddit/179/input_0.png
\_\_HOMEPAGE__/static/input_images/reddit/180/input_0.png
\_\_HOMEPAGE__/static/input_images/reddit/181/input_0.png
\_\_HOMEPAGE__/static/input_images/reddit/182/input_0.png
\_\_HOMEPAGE__/static/input_images/reddit/188/input_0.png
\_\_HOMEPAGE__/static/input_images/reddit/189/input_0.png
\_\_HOMEPAGE__/static/input_images/reddit/190/input_0.png
\_\_HOMEPAGE__/static/input_images/reddit/198/input_0.png
\_\_HOMEPAGE__/static/input_images/reddit/199/input_0.png
\_\_HOMEPAGE__/static/input_images/reddit/205/input_0.png
\_\_HOMEPAGE__/static/input_images/reddit/206/input_0.png

\_\_HOMEPAGE__/static/input_images/shopping/319/input_0.png
\_\_HOMEPAGE__/static/input_images/shopping/351/input_0.png

**Comment by ljang0** [comment]
thanks will take a look

**Comment by ljang0** [comment]
A lot of the image links are forbidden when trying to download from pexels now. Think we should use the local hosting

**Comment by ljang0** [comment]
added header to requests and also local paths. It works with the header request, but the local images might be ideal for long term sustainability of the benchmark

**Review by kohjingyu — APPROVED** [review]
Thanks, looks great!

**Pull request merged**
